version: "3"
services:
  tidb-server01:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4001:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  tidb-server02:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4002:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  tidb-server03:
    image: pingcap/tidb:v6.1.0
    ports:
      - 4003:4000
    command: /tidb-server -store unistore -path "" -lease 0s > tidb.log 2>&1 &
  proxysql:
    image: proxysql/proxysql:latest
    volumes:
    - "./proxysql-load-balance.cnf:/etc/proxysql.cnf"
    - "./proxysql-prepare.sql:/proxysql-prepare.sql"
    depends_on:
      - tidb-server01
      - tidb-server02
      - tidb-server03
    links:
      - tidb-server01
      - tidb-server02
      - tidb-server03
    ports:
    - "6034:6033"